### ISSUE TITLE
Javascript error while starting in iPython

### ISSUE THREAD

**Issue by WaeCo** [lightning-viz/lightning-python#22]
I have two docker container. One with Lightning Server and one with iPython.
The server docker image is based on ```deardooley/lightning-viz```
and iPython with version 3.2.1 is based on ```ipython/scipystack```

I installed Lightning using:
```pip install lightning-python```

then inside Jupyter notebook:

```
from lightning import Lightning
lgn = Lightning(ipython=True, host="http://172.17.9.43:3000", auth=("test", "test"))
```
Output:
```
Javascript error adding output!
SyntaxError: expected expression, got '<'
See your browser Javascript console for more details.
```
Console:
```
SyntaxError: expected expression, got '<'
Stack-Trace:
append_javascript@http://****:8080/user/****/static/notebook/js/outputarea.js?v=20150731232701:626:13
OutputArea.prototype.append_mime_type@http://****:8080/user/****/static/notebook/js/outputarea.js?v=20150731232701:570:32
OutputArea.prototype.append_display_data@http://****:8080/user/****/static/notebook/js/outputarea.js?v=20150731232701:534:13
OutputArea.prototype.append_output@http://****:8080/user/****/static/notebook/js/outputarea.js?v=20150731232701:320:13
OutputArea.prototype.handle_output@http://****:8080/user/****/static/notebook/js/outputarea.js?v=20150731232701:234:9
CodeCell.prototype.get_callbacks/<.iopub.output@http://****:8080/user/****/static/notebook/js/codecell.js?v=20150731232701:456:21
Kernel.prototype._handle_output_message@http://****:8080/user/****/static/services/kernels/kernel.js?v=20150731232701:1012:13
.proxy/i@http://****:8080/user/****/static/components/jquery/jquery.min.js?v=20150731232701:4:5486
Kernel.prototype._handle_iopub_message@http://****:8080/user/****/static/services/kernels/kernel.js?v=20150731232701:1039:20
Kernel.prototype._finish_ws_message@http://****:8080/user/****/static/services/kernels/kernel.js?v=20150731232701:874:1
Kernel.prototype._handle_ws_message/this._msg_queue<@http://****:8080/user/****/static/services/kernels/kernel.js?v=20150731232701:864:39
```

This occurs in Python 2 and 3

**Comment by freeman-lab** [comment]
Thanks for flagging this @WaeCo , the error was created by some comm-based interactivity functionality we added. We fixed the error in the server here (https://github.com/lightning-viz/lightning/commit/3d35136ee4e6af73109777af23274861d1d01d8f) but it hasn't made it's way into the Docker image. I'm just now in the middle of uploading a newer, more official docker image (nothing wrong with the one you used, but we want one under `lightningviz/ligthning` that we'll keep up to date). Will ping here when that's done, hopefully tonight.

**Comment by WaeCo** [comment]
Unfortunately using [master](https://github.com/lightning-viz/lightning/commit/5ff719b07ef22703476b8720478c72272fd0105b) or [v0.1.14](https://github.com/lightning-viz/lightning/commit/e8dfc338a68124700c65d98de04910dceed2e949) directly does not fix it.

**Comment by freeman-lab** [comment]
@WaeCo I just deployed v0.1.14 on heroku at this URL https://lightning-ipython-test.herokuapp.com/, installed the client locally using `pip install lightning-python`, and I don't see the errors when I plot to this host from the IPython notebook

maybe try plotting to this endpoint as well and check if you still see the error? we can definitely reopen the issue on the server repo if needed, but want to make sure I can reproduce first! thanks!

**Comment by WaeCo** [comment]
@freeman-lab ok figured it out. Problem was that I messed up my docker ip config, it works now. 
But still this error shows up if lightning can not connect to the server (resolve the hostname). A proper error output would be nice.

**Comment by freeman-lab** [comment]
Thanks for the feedback, tried to add some better and earlier messages on failed connections here https://github.com/lightning-viz/lightning-python/commit/951c2d1cd4fd8640114b16bf3388c50957bcdd68
